# Do not edit this file directly. It has been autogenerated from
# src\pydabpumps\api_base_async.py
"""api_base.py: DabPumps API for DAB Pumps integration."""

import base64
import copy
import hashlib
import jwt
import math
import os
import warnings
import asyncio
import httpx
import json
import logging
import re
import time

from dataclasses import replace
from datetime import datetime, timedelta, timezone
from enum import Enum, StrEnum
from typing import Any
from urllib.parse import urlparse, parse_qs
from uuid import UUID


from .const import (
    DABSSO_API_URL,
    DCONNECT_API_URL,
    DCONNECT_API_DOMAIN,
    DCONNECT_ACCESS_TOKEN_COOKIE,
    DCONNECT_ACCESS_TOKEN_VALID,
    DCONNECT_REFRESH_TOKEN_COOKIE,
    DCONNECT_REFRESH_TOKEN_VALID,
    DABCS_INIT_URL,
    DABCS_API_URL,
    DABCS_API_DOMAIN,
    DABCS_ACCESS_TOKEN_VALID,
    DABCS_REFRESH_TOKEN_VALID,
    DABSSO_ACCESS_TOKEN_VALID,
    DABSSO_REFRESH_TOKEN_VALID,
    H2D_APP_CLIENT_ID,
    H2D_APP_CLIENT_SECRET,
    H2D_APP_DABCS_AUTH,
    H2D_APP_REDIRECT_URI,
    DABLIVE_APP_CLIENT_ID,
    DABLIVE_APP_CLIENT_SECRET,
    DABLIVE_APP_REDIRECT_URI,
    DABLIVE_APP_DABCS_AUTH,
    DCONNECT_APP_CLIENT_ID,
    DCONNECT_APP_CLIENT_SECRET,
    DCONNECT_APP_DABCS_AUTH,
    DCONNECT_WEB_CLIENT_ID,
    DCONNECT_WEB_CLIENT_SECRET,
    DCONNECT_WEB_REDIRECT_URI,
    LOGIN_REPEAT_TIMEOUT_MIN,
    LOGIN_REPEAT_TIMEOUT_MAX,
    DEVICE_ATTR_EXTRA,
    STATUS_UPDATE_HOLD,
    HTTPX_REQUEST_TIMEOUT,
    utcnow,
    utcmin,
)

from .data import (
    DabPumpsApiFlag,
    DabPumpsError,
    DabPumpsConnectError,
    DabPumpsAuthError,
    DabPumpsDataError,
    DabPumpsStatusCode,
    DabPumpsUserRole,
    DabPumpsParamType,
    DabPumpsInstall,
    DabPumpsDevice,
    DabPumpsDeviceConfig,
    DabPumpsDeviceState,
    DabPumpsParams,
    DabPumpsStatus,
    DabPumpsLogin,
    DabPumpsFetch,
    DabPumpsAuth,
    DabPumpsLoginInfo,
    DabPumpsAccessTokenInfo,
    DabPumpsRefreshTokenInfo,
    DabPumpsSessionInfo,
    DabPumpsHistoryItem,
    DabPumpsHistoryDetail,
)

from .tasks import (
    AsyncTaskHelper,
    TaskHelper,
)
import threading

_LOGGER = logging.getLogger(__name__)


# DabPumps api to detect device and get device info, fetch the actual data from the device, and parse it
class DabPumpsBase:
    
    def __init__(self, username, password, client:httpx.Client=None, login_info:DabPumpsLoginInfo=None, access_token_info:DabPumpsAccessTokenInfo=None, refresh_token_info:DabPumpsRefreshTokenInfo=None, flags:dict[DabPumpsApiFlag,Any] = {}):
        # Configuration
        self._username: str = username
        self._password: str = password

        # Login data
        self._login_active: bool = False
        self._login_info: DabPumpsLoginInfo = login_info or DabPumpsLoginInfo()
        self._access_token_info: DabPumpsAccessTokenInfo = access_token_info or DabPumpsAccessTokenInfo()
        self._refresh_token_info: DabPumpsRefreshTokenInfo = refresh_token_info or DabPumpsRefreshTokenInfo()
        self._session_info: DabPumpsSessionInfo = DabPumpsSessionInfo()
        
        # Automatic refresh of access token or re-login
        self._login_handler_start = flags.get(DabPumpsApiFlag.LOGIN_HANDLER_START, True)
        self._login_handler_task = TaskHelper(
            name="Relogin handler", 
            action=self.login, 
            repeat_timeout_min=LOGIN_REPEAT_TIMEOUT_MIN, 
            repeat_timeout_max=LOGIN_REPEAT_TIMEOUT_MAX
        )

        # Retrieved data
        self._install_map: dict[str, DabPumpsInstall] = {}              # install_id => install
        self._device_map: dict[str, DabPumpsDevice] = {}                # serial => device def
        self._device_config_map: dict[str, DabPumpsDeviceConfig] = {}   # config_id => device config
        self._device_state_map: dict[str, DabPumpsDeviceState] = {}     # serial => device state
        self._string_map: dict[str, str] = {}                           # key => translation
        self._string_map_lang: str = None

        # Internal admin of which status values have a pending update
        self._status_update_map: dict[str, datetime] = {}               # id(serial+key) -> datetime

        # Http Client; we keep the same client for the whole life of the api instance.
        self._http_client: httpx.Client = client or httpx.Client()
        self._http_client_close = False if client else True     # Do not close an external passed client

        # Locks to protect certain operations from being called from multiple threads
        self._login_lock = threading.Lock()

        # To pass diagnostics data back to our parent
        self._diagnostics_callback = None


    def set_diagnostics(self, callback):
        """Pass diagnostics data back to our parent"""
        self._diagnostics_callback = callback


    @staticmethod
    def create_id(*args):
        str = '_'.join(args).strip('_')
        str = re.sub(' ', '_', str)
        str = re.sub('[^a-z0-9_-]+', '', str.lower())
        return str            
    
    @property
    def login_active(self) -> bool:
        return self._login_active
    
    @property
    def login_info(self) -> DabPumpsLoginInfo:
        return self._login_info
    
    @property
    def access_token_info(self) -> DabPumpsAccessTokenInfo:
        return self._access_token_info
    
    @property
    def refresh_token_info(self) -> DabPumpsRefreshTokenInfo:
        return self._refresh_token_info
    
    @property
    def install_map(self) -> dict[str, DabPumpsInstall]:
        return self._install_map
    
    @property
    def device_map(self) -> dict[str, DabPumpsDevice]:
        return self._device_map
    
    @property
    def device_config_map(self) -> dict[str, DabPumpsDeviceConfig]:
        return self._device_config_map
    
    @property
    def device_state_map(self) -> dict[str, DabPumpsDeviceState]:
        return self._device_state_map
    
    @property
    def string_map(self) -> dict[str, str]:
        return self._string_map
    
    @property
    def string_map_lang(self) -> str:
        return self._string_map_lang


    @property
    def closed(self) -> bool:
        """Returns whether the DabPumps api has been closed."""
        if self._http_client:
            return self._http_client.is_closed
        else:
            return True
        

    def close(self):
        """Safely logout and close all client handles"""
        self.logout()

        if self._http_client is not None and self._http_client_close:
            self._http_client.close()
            self._http_client = None


    def login(self, test_method:DabPumpsLogin=None):
        """
        Login to DAB Pumps by trying each of the possible login methods.
        Guards for calls from multiple threads.
        """

        # Only one thread at a time can check token cookie and do subsequent login if needed.
        # Once one thread is done, the next thread can then check the (new) token cookie.
        with self._login_lock:
            self._login(test_method=test_method)

            # If needed, start our login_refresh_handler thread
            if self._login_handler_start and not self._login_handler_task.running:
                self._login_handler_task.start()


    def _login(self, test_method:DabPumpsLogin=None):
        """Login to DAB Pumps by trying each of the possible login methods"""        

        # We have four possible login methods that all seem to work for both DConnect (non-expired) and for DAB Live
        # - First try to keep using the access token
        # - Next, try to refresh that token.
        # - Then, try the method that succeeded last time!
        # - Finally try all login methods
        # For testing we can force to use a specific method
        error = None
        
        if test_method is None:
            methods = [DabPumpsLogin.ACCESS_TOKEN, DabPumpsLogin.REFRESH_TOKEN, self._login_info.login_method, DabPumpsLogin.H2D_APP, DabPumpsLogin.DABLIVE_APP, DabPumpsLogin.DCONNECT_APP]  
            # DabPumpsLogin.DCONNECT_WEB removed because it does not support Wamp/Push data
        else:
            methods = [test_method]
            
        for method in methods:
            try:
                match method:
                    case DabPumpsLogin.ACCESS_TOKEN:
                        # Try to keep using the Access Token
                        success = self._login_access_token()
                    case DabPumpsLogin.REFRESH_TOKEN:
                        # Try to refresh the token
                        success = self._login_refresh_token()
                    case DabPumpsLogin.H2D_APP:
                        # Try the procedure of the H2D app (most up to date)
                        success = self._login_dabsso(method)
                    case DabPumpsLogin.DABLIVE_APP: 
                        # Try the simplest method
                        success = self._login_dabsso(method)
                    case DabPumpsLogin.DCONNECT_APP:
                        # Try the method that uses 2 steps
                        success = self._login_dconnect_app()
                    case DabPumpsLogin.DCONNECT_WEB:
                        # Finally try the most complex and unreliable one
                        success = self._login_dconnect_web()
                        # success = await self._login_dabsso(method)  # Experimental, does not work yet...
                    case _:
                        # No previously known login method was set yet
                        success =  False

                if success:
                    # if we reached this point then a login method succeeded
                    self._login_active = True
                    return 
            
            except Exception as ex:
                error = ex

                # Clear any previous login cookies and tokens before trying the next method
                self._logout(context="login", method=method)

        # if we reached this point then all methods failed.
        if error:
            raise error
        

    def _login_access_token(self) -> bool:
        """Inspect whether the access token is still valid"""

        match self._login_info.auth_method:
            case DabPumpsAuth.COOKIE: access_token = self._http_client.cookies.get(name=DCONNECT_ACCESS_TOKEN_COOKIE, domain=DCONNECT_API_DOMAIN)
            case DabPumpsAuth.HEADER: access_token = self._access_token_info.token
            case _: access_token = None

        if not access_token or not self._access_token_info.expiry:
            # No acces-token to check; silently continue to the next login method (token refresh)
            return False

        # Dab Pumps seems to ignore the expiry field inside the token, using only
        # the expires_in field that was passed alongside the token.
        if utcnow() >= self._access_token_info.expiry:
            _LOGGER.debug(f"Access-Token expired")
            return False    # silently continue to the next login method (token refresh)

        # Re-use this access token
        context = f"login access_token reuse"
        self._update_diagnostics(utcnow(), context, None, None, self._access_token_info)

        self._login_handler_task.schedule(self._access_token_info.expiry)

        #_LOGGER.debug(f"Reuse the access-token")
        return True


    def _login_refresh_token(self) -> bool:
        """Attempty to refresh the access token"""

        match self._login_info.auth_method:
            case DabPumpsAuth.COOKIE: refresh_token = self._http_client.cookies.get(name=DCONNECT_REFRESH_TOKEN_COOKIE, domain=DCONNECT_API_DOMAIN)
            case DabPumpsAuth.HEADER: refresh_token = self._refresh_token_info.token
            case _: refresh_token = None

        if not refresh_token:
            # No refresh-token; silently continue to the next login method
            return False
        
        if self._login_info.auth_method == DabPumpsAuth.COOKIE:
            # The tokens cookies should automatically be refreshed during periodic calls.
            # If we get to this point then somehow the access-token and refresh-token cookies
            # have expired; silently continue to the next login method 
            return False
        
        # Don't bother to check the contents of the refresh token, 
        # just attempt to request a new access token via the refresh token
        context = f"login access_token refresh"
        request = {
            "method": "POST",
            "url": DABSSO_API_URL + '/auth/realms/dwt-group/protocol/openid-connect/token',
            "headers": {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            "data": {
                'grant_type': 'refresh_token',
                'refresh_token': self._refresh_token_info.token, 
                'client_id': self._refresh_token_info.client_id or "",
                'client_secret': self._refresh_token_info.client_secret or "",
            },
        }
        
        _LOGGER.debug(f"Try refresh the access-token")
        result = self._send_request(context, request)

        # Store access-token in variable so it will be added as Authorization header in calls to DABCS and DConnect
        # We do not need to store the new access-token as cookie, those take care of their own refresh
        default_access_expires_in = DABCS_ACCESS_TOKEN_VALID if self.login_info.fetch_method==DabPumpsFetch.DABCS else DCONNECT_ACCESS_TOKEN_VALID
        default_refresh_expires_in = DABCS_REFRESH_TOKEN_VALID if self.login_info.fetch_method==DabPumpsFetch.DABCS else DCONNECT_REFRESH_TOKEN_VALID

        self._access_token_info = DabPumpsAccessTokenInfo(
            token = self._validate_token( result.get('access_token') ),
            expires_in = result.get('expires_in') or default_access_expires_in,
            expiry = self._calculate_expiry( result.get('expires_in'), default_access_expires_in ),
        )
        self._refresh_token_info = DabPumpsRefreshTokenInfo(
            token = self._validate_token( result.get('refresh_token') ),
            expires_in = result.get('expires_in') or default_refresh_expires_in,
            expiry = self._calculate_expiry( result.get('refresh_expires_in'), default_refresh_expires_in ),
            client_id = self._refresh_token_info.client_id,
            client_secret = self._refresh_token_info.client_secret,
        )

        if not self._access_token_info.token or not self._refresh_token_info.token:
            error = f"No tokens found in response from {request["url"]}"
            _LOGGER.debug(error)    # logged as warning after last retry
            raise DabPumpsAuthError(error)

        self._login_handler_task.schedule(self._access_token_info.expiry)

        # The refresh of the tokens succeeded
        _LOGGER.debug(f"Refreshed the access-token; original login used method {self._login_info.login_method}")
        return True


    def _login_dabsso(self, method:DabPumpsLogin) -> bool:
        """
        Login to DAB Pumps via the unified dabsso method as used by the H2D app and DAB Live app
        """

        # Step 0: generate an unique state and a code challenge
        state_bytes = os.urandom(16)
        state_b64 = base64.urlsafe_b64encode(state_bytes).decode('utf-8').rstrip('=')
        state_guid = str(UUID(bytes=state_bytes))

        openid_code_bytes = os.urandom(86)
        openid_code_verifier = base64.urlsafe_b64encode(openid_code_bytes).decode('utf-8').rstrip('=')
        openid_hashed_verifier = hashlib.sha256(openid_code_verifier.encode('utf-8')).digest()
        openid_code_challenge = base64.urlsafe_b64encode(openid_hashed_verifier).decode('utf-8').rstrip('=')

        match method:
            case DabPumpsLogin.DABLIVE_APP:
                openid_client_id = DABLIVE_APP_CLIENT_ID
                openid_client_secret = DABLIVE_APP_CLIENT_SECRET
                openid_redirect_uri = DABLIVE_APP_REDIRECT_URI
                openid_state = state_b64

            case DabPumpsLogin.DCONNECT_WEB:    # Experimental in _login_dabsso()
                openid_client_id = DCONNECT_WEB_CLIENT_ID
                openid_client_secret = DCONNECT_WEB_CLIENT_SECRET
                openid_redirect_uri = DCONNECT_WEB_REDIRECT_URI
                openid_state = state_b64

            case DabPumpsLogin.H2D_APP | _:
                openid_client_id = H2D_APP_CLIENT_ID
                openid_client_secret = H2D_APP_CLIENT_SECRET
                openid_redirect_uri = H2D_APP_REDIRECT_URI
                openid_state = state_b64

        # Step 1: get login url
        context = f"login {method} openid-connect auth"
        request = {
            "method": "GET",
            "url": DABSSO_API_URL + '/auth/realms/dwt-group/protocol/openid-connect/auth',
            'params': {
                'client_id': openid_client_id,
                'response_type': 'code',
                'state': openid_state,
                'scope': 'openid profile email phone',
                'code_challenge': openid_code_challenge,
                'code_challenge_method': 'S256',
                'redirect_uri': openid_redirect_uri,
            },
            "flags": {
                'redirects': False,
            }
        }

        _LOGGER.debug(f"Try login with {method}; connect")
        text = self._send_request(context, request)
        
        if not text.startswith(openid_redirect_uri):
            # We received a login page containing a form
            match = re.search(r'action\s?=\s?\"(.*?)\"', text, re.MULTILINE)
            if not match:    
                error = f"Unexpected response while retrieving openid-connect from {request["url"]}: {text}"
                _LOGGER.debug(error)    # logged as warning after last retry
                raise DabPumpsAuthError(error)
            
            auth_url = match.group(1).replace('&amp;', '&')
        else:
            # We received a location header containing the openid-code
            auth_url = None
            location_str = text
        
        # Step 2: Authenticate (if still needed)
        if auth_url is not None:
            context = f"login {method} authenticate"
            request = {
                "method": "POST",
                "url": auth_url,
                "headers": {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                "data": {
                    'username': self._username, 
                    'password': self._password,
                },
                "flags": {
                    'redirects': False,
                }
            }
            
            _LOGGER.debug(f"Try login with {method}; authenticate '{self._username}'")
            location_str = self._send_request(context, request)

        # Returned value is a redirect location containing state and session_state
        if not location_str.startswith(openid_redirect_uri) or not "code=" in location_str:
            error = f"Unexpected response while authenticating from {request["url"]}: {text}"
            _LOGGER.debug(error)    # logged as warning after last retry
            raise DabPumpsAuthError(error)
        
        location_url = urlparse(location_str)
        openid_state_rsp = parse_qs(location_url.query).get('state')[0]
        openid_code = parse_qs(location_url.query).get('code')[0]

        if openid_state_rsp != openid_state:
            _LOGGER.debug(f"Unexpected state value in response while authenticating: '{openid_state_rsp}', expected '{openid_state}")

        # Step 3: Get Access and Refresh Tokens
        context = f"login {method} openid-connect token"
        request = {
            "method": "POST",
            "url": DABSSO_API_URL + '/auth/realms/dwt-group/protocol/openid-connect/token',
            "headers": {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            "data": {
                'grant_type': 'authorization_code',
                'code': openid_code, 
                'code_verifier': openid_code_verifier,
                'client_id': openid_client_id,
                'redirect_uri': openid_redirect_uri,
            },
            "flags": {
                'redirects': False,
            }
        }
        
        _LOGGER.debug(f"Try login with {method}; tokens")
        result = self._send_request(context, request)
        
        default_access_expires_in = DABCS_ACCESS_TOKEN_VALID if self.login_info.fetch_method==DabPumpsFetch.DABCS else DCONNECT_ACCESS_TOKEN_VALID
        default_refresh_expires_in = DABCS_REFRESH_TOKEN_VALID if self.login_info.fetch_method==DabPumpsFetch.DABCS else DCONNECT_REFRESH_TOKEN_VALID

        self._access_token_info = DabPumpsAccessTokenInfo(
            token = self._validate_token( result.get('access_token') ),
            expires_in = result.get('expires_in') or default_access_expires_in,
            expiry = self._calculate_expiry( result.get('expires_in'), DABSSO_ACCESS_TOKEN_VALID ),
        )
        self._refresh_token_info = DabPumpsRefreshTokenInfo(
            token = self._validate_token( result.get('refresh_token') ),
            expires_in = result.get('expires_in') or default_refresh_expires_in,
            expiry = self._calculate_expiry( result.get('refresh_expires_in'), DABSSO_REFRESH_TOKEN_VALID ),
            client_id = openid_client_id,
            client_secret = openid_client_secret,
        )

        if not self._access_token_info.token:
            error = f"No tokens found in response from {request["url"]}"
            _LOGGER.debug(error)    # logged as warning after last retry
            raise DabPumpsAuthError(error)
       
        # if we reach this point then the token was OK
        self._login_info = DabPumpsLoginInfo(
            login_method = method,
        )
        self._login_handler_task.schedule(self._access_token_info.expiry)

        _LOGGER.debug(f"Login succeeded using method {self._login_info.login_method}")
        return True

        
    def _login_dconnect_app(self) -> bool:
        """Login to DAB Pumps via the method as used by the DConnect app"""

        # Step 1: get authorization token
        openid_client_id = DCONNECT_APP_CLIENT_ID
        openid_client_secret = DCONNECT_APP_CLIENT_SECRET

        context = f"login DConnect_app"
        request = {
            "method": "POST",
            "url": DABSSO_API_URL + f"/auth/realms/dwt-group/protocol/openid-connect/token",
            "headers": {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            "data": {
                'client_id': openid_client_id,
                'client_secret': openid_client_secret,
                'scope': 'openid',
                'grant_type': 'password',
                'username': self._username, 
                'password': self._password 
            },
        }
        
        _LOGGER.debug(f"Try login with DConnect (app); authenticate '{self._username}'")
        result = self._send_request(context, request)

        self._access_token_info = DabPumpsAccessTokenInfo(
            token = self._validate_token( result.get('access_token') ),
            expires_in = result.get('expires_in') or DCONNECT_ACCESS_TOKEN_VALID,
            expiry = self._calculate_expiry( result.get('expires_in'), DCONNECT_ACCESS_TOKEN_VALID ),
        )
        self._refresh_token_info = DabPumpsRefreshTokenInfo(
            token = self._validate_token( result.get('refresh_token') ),
            expires_in = result.get('expires_in') or DCONNECT_REFRESH_TOKEN_VALID,
            expiry = self._calculate_expiry( result.get('refresh_expires_in'), DCONNECT_REFRESH_TOKEN_VALID ),
            client_id = openid_client_id,
            client_secret = openid_client_secret,
        )

        if not self._access_token_info.token:
            error = f"No tokens found in response from {request["url"]}"
            _LOGGER.debug(error)    # logged as warning after last retry
            raise DabPumpsAuthError(error)

        # if we reach this point then the token was OK
        self._login_info = DabPumpsLoginInfo(
            login_method = DabPumpsLogin.DCONNECT_APP,
        )
        self._login_handler_task.schedule(self._access_token_info.expiry)

        _LOGGER.debug(f"Login succeeded using method {self._login_info.login_method}")
        return True


    def _login_dconnect_web(self) -> bool:
        """Login to DAB Pumps via the method as used by the DConnect website"""

        # Step 1: get login url
        context = f"login DConnect_web home"
        request = {
            "method": "GET",
            "url": DCONNECT_API_URL,
        }

        _LOGGER.debug(f"Try login with DConnect (web); retrieve login page")
        text = self._send_request(context, request)
        
        match = re.search(r'action\s?=\s?\"(.*?)\"', text, re.MULTILINE)
        if not match:    
            error = f"Unexpected response while retrieving login url from {request["url"]}: {text}"
            _LOGGER.debug(error)    # logged as warning after last retry
            raise DabPumpsAuthError(error)
        
        # Step 2: Login
        context = f"login DConnect_web login"
        request = {
            "method": "POST",
            "url": match.group(1).replace('&amp;', '&'),
            "headers": {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            "data": {
                'username': self._username, 
                'password': self._password 
            },
        }
        
        _LOGGER.debug(f"Try login with DConnect (web); authenticate '{self._username}'")
        self._send_request(context, request)

        # Verify the client access_token cookie has been set
        access_token = self._http_client.cookies.get(name=DCONNECT_ACCESS_TOKEN_COOKIE, domain=DCONNECT_API_DOMAIN)
        if not access_token:
            error = f"No access token found in response from {request["url"]}"
            _LOGGER.debug(error)    # logged as warning after last retry
            raise DabPumpsAuthError(error)

        # if we reach this point without exceptions then login was successfull
        # Cookie for access_token is already set by the last call
        # No need to remember access-token, we never need to pass it as header with this login method
        self._access_token_info = DabPumpsAccessTokenInfo(
            token = access_token,
            expires_in = None,
            expiry = datetime.max,  # Always let access-token expiry check succeed,
        )
        self._refresh_token_info = DabPumpsRefreshTokenInfo(
            token = None,
            expires_in = None,
            expiry = datetime.max, # Always let refresh-token expiry check succeed,
            client_id = None,
            client_secret = None,
        )

        # Set other login parameters
        self._login_info = DabPumpsLoginInfo(
            login_method = DabPumpsLogin.DCONNECT_WEB,
        )
        self._login_handler_task.schedule(self._access_token_info.expiry)

        _LOGGER.debug(f"Login succeeded using method {self._login_info.login_method}")
        return True
    

    def _start_user_session(self) -> bool:
        """
        Open/Start a new session. Needed to open a direct socket connection
        """
        if self._session_info.key is not None and self._session_info.wstoken is not None:
            # Already have the session key and websocket token
            return True

        # Check we have a valid access_token, otherwise we cannot do the call to start the user session
        if not self._access_token_info.is_valid:
            return False
        
        # User session is not supported via DCONNECT_WEB login methods
        match self._login_info.login_method:
            case None: return False
            case DabPumpsLogin.H2D_APP:      self._session_info.dabcs_auth = H2D_APP_DABCS_AUTH
            case DabPumpsLogin.DABLIVE_APP:  self._session_info.dabcs_auth = DABLIVE_APP_DABCS_AUTH
            case DabPumpsLogin.DCONNECT_APP: self._session_info.dabcs_auth = DCONNECT_APP_DABCS_AUTH
            case DabPumpsLogin.DCONNECT_WEB | _:
                raise DabPumpsError(f"Subscribe to push data is not supported for login method {self._login_info.login_method}")
        
        # Step 1: start session
        context = f"user session start {self._username.lower()}"
        request = {
            "method": "POST",
            "url": DABCS_API_URL + '/mobile/v1/user/session?destroyothers=1',
            "headers": {
                "x-dabcs-auth": self._session_info.dabcs_auth,
                "x-dabcs-device": self._session_info.dabcs_device,
            },
        }

        _LOGGER.debug(f"User session start for '{self._username}'")
        raw = self._send_request(context, request)  

        # Process the resulting raw data
        # For DabCS:
        # {
        #   "session_key": "5345cd70-6936-11f1-aa20-59153c4f37a5"
        # }
        self._session_info.key = raw.get('session_key')
            
        if self._session_info.key is None:
            return False

        # Step 2: get wstoken
        context = f"user session wstoken {self._username.lower()}"
        request = {
            "method": "POST",
            "url": DABCS_API_URL + '/mobile/v1/user/wstoken',
            "headers": {
                "x-dabcs-auth": self._session_info.dabcs_auth,
                "x-dabcs-device": self._session_info.dabcs_device,
                "x-session-token": self._session_info.key,
            }
        }

        _LOGGER.debug(f"User session get wstoken")
        raw = self._send_request(context, request)  

        # Process the resulting raw data
        # For DabCS:
        # {
        #   "token": "NTcyYzc1MWQ5ZGI4OGQ5NGY4MGUyNWY3ZmIwNjJmYzU0NC53ICYwJwo8MXdvd2IzM2xjZGdjeDRhNDB4YWU2bXg0NmFheGw3ZzY3bWIzbGZmZnd5dzw7JiE0OTk0ITw6Owo8MSZ3bw53N2RsZWFsYWF4bTMwYHhhYzZkeG1jMWZ4bGxhZzRiYWxkYDFsd3l3ZDY0YDQzbGd4ZTBnMXhhYjNieG00YmR4NmRsMGxsY2NkbWFtdwh5dzAtJXdvZGJtZG1gYGVsZWZkZyg="
        # }
        self._session_info.wstoken = raw.get('token')

        if self._session_info.wstoken is None:
            return False        
        
        return True

        
    def _stop_user_session(self) -> bool:
        """
        Close/Stop session.
        """
        if self._session_info.key is None:
            # No current session
            return True

        # Check we have a valid access_token, otherwise we cannot do the call to stop the user session
        if not self._access_token_info.is_valid:
            return False
        
        # User session works with all login methods, except DCONNECT_WEB or when not logged in
        if self._login_info.login_method in [None, DabPumpsLogin.DCONNECT_WEB]:
            return False
        
        try:
            context = f"user session stop {self._username.lower()}"
            request = {
                "method": "DELETE",
                "url": DABCS_API_URL + '/mobile/v1/user/session',
                "headers": {
                    "x-dabcs-auth": self._session_info.dabcs_auth,
                    "x-dabcs-device": self._session_info.dabcs_device,
                    "x-session-token": self._session_info.key
                }
            }

            _LOGGER.debug(f"User session stop for '{self._username}'")
            raw = self._send_request(context, request)  

        except:
            pass    # Ignore any errors

        finally:
            self._session_info.key = None
            self._session_info.wstoken = None

        return True


    def logout(self):
        """Logout from DAB Pumps"""

        # Stop token refresh_handler
        if self._login_handler_task.running:
            self._login_handler_task.stop()

        # Only one thread at a time can check token cookie and do subsequent login or logout if needed.
        # Once one thread is done, the next thread can then check the (new) token cookie.
        with self._login_lock:
            self._logout(context="", method=None)


    def _logout(self, context: str, method: DabPumpsLogin|None = None):
        # Note: do not call 'async with self._login_lock' here.
        # It will result in a deadlock as login calls _logout from within its lock

        # Sanitize parameters
        context = context.lower() if context else ""

        # Reduce amount of tracing to only when we are actually logged-in
        if self._login_active and method not in [DabPumpsLogin.ACCESS_TOKEN]:
            self._login_active = False
            _LOGGER.debug(f"Logout")

        # Home Assistant will issue a warning when calling aclose() on the async aiohttp client.
        # Instead of closing we will simply forget the access token. The result is that on a next
        # request, the client will act like it is a new one.
        self._http_client.cookies.delete(name=DCONNECT_ACCESS_TOKEN_COOKIE, domain=DCONNECT_API_DOMAIN)
        self._access_token_info = DabPumpsAccessTokenInfo(
            token = None,
            expires_in = None,
            expiry = None,
        )

        # Only clear refresh token when refresh of access token has failed
        if method in [DabPumpsLogin.REFRESH_TOKEN]:
            self._http_client.cookies.delete(name=DCONNECT_REFRESH_TOKEN_COOKIE, domain=DCONNECT_API_DOMAIN)
            self._refresh_token_info = DabPumpsRefreshTokenInfo(
                token = None,
                expires_in = None,
                expiry = None,
                client_id = None,
                client_secret = None,
            )

        # Only clear login_method when called from an external context
        # or when actual data retrieval failed. Not when we are in a login context.
        if not context.startswith("login"):
            self._login_info = DabPumpsLoginInfo(
                login_method = None
            )

        # Trigger repeated re-login attempts (will be cancelled if this is a real logout)
        self._login_handler_task.schedule(None)   


    def _validate_token(self, token: str|None) -> str:
        try:
            jwt.decode(jwt=token, options={"verify_signature": False})
            return token
        except:            
            return ""


    def _calculate_expiry(self, expires_in: int|None, default: int) -> datetime:
        # Increase margin based on length of expires_in
        expires_in = expires_in or default
        
        if   expires_in <       60*60: margin =       60  # expires_in up to 60 minutes leads to margin of 1 minute
        elif expires_in <    24*60*60: margin =    30*60  # expires_in up to 1 day leads to margin of 30 minutes
        elif expires_in < 10*24*60*60: margin = 12*60*60  # expires_in up to 10 days leads to margin of 12 hours
        else:                          margin = 24*60*60  # expires_in over 10 days leads to margin of 1 day

        return utcnow() + timedelta(seconds=expires_in) - timedelta(seconds=margin)



    def fetch_install_list(self):
        """
        Get installation list
        This fills:
          install_map    (details for each install)
        """

        # Retrieve data via REST request
        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS:    url = DABCS_API_URL + '/mobile/v1/installations?include=current_user_subscription'
            case DabPumpsFetch.DCONNECT: url = DCONNECT_API_URL + '/api/v1/installation' # or DABPUMPS_API_URL + '/getInstallationList'

        context = f"installations {self._username.lower()}"
        request = {
            "method": "GET",
            "url": url,
        }

        _LOGGER.debug(f"Retrieve installation list for '{self._username}'")
        raw = self._send_request(context, request)  

        # Process the resulting raw data
        # For DabCS:
        # {
        #   "installations": [
        #     { "name": "some_str", "installation_id": "some_guid", "metadata": { ... }, "current_user_role": "role", "current_user_subscription": { "subscription_due_date": "2026-07-15T22:57:46.077Z", "subscription_type": "STANDARD", "status": "ACTIVE", ... }, ... }
        #   ]
        # }
        # For DConnect:
        # {
        #   "values": [     # or "rows": [
        #     { "name": "some_str", "installation_id": "some_guid", "user_role": "role", "contract_due_date": "2026-07-15T22:57:46.077Z", "contract_type": "STANDARD"... }
        #   ]
        # }
        install_map = {}
        installations = raw.get('installations') or raw.get('values') or raw.get('rows') or []
        
        for install_idx, installation in enumerate(installations):
            
            install_id = installation.get('installation_id') or ''
            install_name = installation.get('name') or installation.get('description') or f"installation {install_idx}"
            install_meta = installation.get('metadata') or {}
            subscription = installation.get('current_user_subscription') or {}

            _LOGGER.debug(f"Installation found: {install_name}")
            install = DabPumpsInstall(
                id = install_id,
                name = install_name,
                description = installation.get('description') or '',
                company = installation.get('company') or install_meta.get('company') or '',
                address = installation.get('address') or install_meta.get('address') or '',
                role = installation.get('current_user_role') or installation.get('user_role') or DabPumpsUserRole.CUSTOMER_FREE,
                subscr_ts = subscription.get('subscription_due_date') or installation.get('contract_due_date') or None,
                devices = len(installation.get('dums') or []),
            )
            install_map[install_id] = install

        # Sanity check. # Never overwrite a known install_map with empty lists
        if len(install_map)==0:
            raise DabPumpsDataError(f"No installations found in data")

        # Remember this data
        self._install_map = install_map


    def fetch_install_details(self, install_id: str):
        """
        Fetch all details from an installation.
        This fills:
          device_map           (details for each device)
          device_config_map    (config metadata for each device)
          device_state_map     (inital statuses for each device)
        """

        # Retrieve list of devices within this install
        raw = self._fetch_install_devices(install_id)

        # First retrieve all device configs
        for config_id in [ d.config_id for d in self._device_map.values() if d.install_id==install_id ]:
            self._fetch_device_config(config_id, raw_install_data=raw)

        # Next retrieve inital device statuses
        for serial in [ d.serial for d in self._device_map.values() if d.install_id==install_id ]:
            self._fetch_device_state(serial, raw_install_data=raw)

            # Finally, derive extra device details
            self._derive_device_details(serial)


    def fetch_install_statuses(self, install_id: str):
        """
        Fetch the statuses for all devices in an installation
        This updates:
          device_state_map     (inital statuses for each device)
        """

        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS:
                # Returns statuses for all devices in one call
                context = f"statuses {install_id}"
                request = { "method": "GET", "url": DABCS_API_URL + f"/mobile/v1/installations/{install_id}/dums" }
        
                _LOGGER.debug(f"Retrieve installation statuses")
                raw = self._send_request(context, request)

            case DabPumpsFetch.DCONNECT:
                # Needs to retrieve data per device
                raw = None

        for serial in [ d.serial for d in self._device_map.values() if d.install_id==install_id ]:
            self._fetch_device_state(serial, raw_install_data=raw)
        
        
    def _fetch_install_devices(self, install_id: str):
        """Get installation details"""

        # Retrieve data via REST request
        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS:    url = DABCS_API_URL + f"/mobile/v1/installations/{install_id}/dums?include_configuration=true"
            case DabPumpsFetch.DCONNECT: url = DCONNECT_API_URL + f"/api/v1/installation/{install_id}" # or DABPUMPS_API_URL + f"/getInstallation/{install_id}"

        context = f"installation {install_id}"
        request = {
            "method": "GET",
            "url": url,
        }
        
        _LOGGER.debug(f"Retrieve installation details")
        raw = self._send_request(context, request)

        # Process the resulting raw data
        # For DabCS:
        # {
        #   "dums": [
        #     { "configuration_id": "guid3", "serial": "some_str", "status": { ... }, ... }
        #   ],
        #   "configurations": [
        #     { "guid": { "family": "str", "ProductName": "str", "params": [...], ... } }
        #   ]
        # }
        # For DConnect:
        # {
        #   "installation_id": "guid1",
        #   "dums": [
        #     { "configuration_id": "guid3", "serial": "some_str", ... }
        #   ]
        # }
        device_map = {}
        ins_dums = raw.get('dums') or []

        for dum_idx, dum in enumerate(ins_dums):
            dum_id = dum.get('dum_id') or ''
            dum_serial = dum.get('serial') or ''
            dum_name = dum.get('name') or dum.get('ProductName') or f"device {dum_idx}"
            dum_product = dum.get('ProductName') or dum.get('distro_embedded') or dum.get('distro')  or f"device {dum_idx}"
            dum_version = dum.get('configuration_name') or dum.get('distro_embedded') or dum.get('distro')  or dum.get('distro') or ''
            dum_config = dum.get('configuration_id') or ''

            if not dum_id: 
                raise DabPumpsDataError(f"Could not find installation attribute 'dum_id'")
            if not dum_serial: 
                raise DabPumpsDataError(f"Could not find installation attribute 'serial'")
            if not dum_config: 
                raise DabPumpsDataError(f"Could not find installation attribute 'configuration_id'")

            device = DabPumpsDevice(
                vendor = 'DAB Pumps',
                name = dum_name,
                id = dum_id,
                serial = dum_serial,
                product = dum_product,
                hw_version = dum_version,
                config_id = dum_config,
                install_id = install_id,
                # Attributes below are retrieved later on via fetch_device_details
                sw_version = None,
                mac_address = None,
            )
            device_map[dum_serial] = device
            
            _LOGGER.debug(f"Device found: {dum_name} with serial {dum_serial}")
            
        # Sanity check. # Never overwrite a known device_map
        if len(device_map) == 0:
            raise DabPumpsDataError(f"No devices found for installation id {install_id}")

        # Remember/update the found map.
        self._device_map.update(device_map)

        # Cleanup devices from this installation that are no longer needed in _device_map
        candidate_list = [ k for k,v in self._device_map.items() if v.install_id == install_id and not k in device_map ]
        for key in candidate_list:
            self._device_map.pop(key, None)

        return raw


    def _fetch_device_config(self, config_id: str, raw_install_data: dict|None = None):
        """Fetch the statuses for a DAB Pumps device, which then constitues the Sensors"""

        # Retrieve data via REST request
        conf = {}
        conf_id = None

        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS:
                if raw_install_data is None:
                    raise DabPumpsError("No raw install data was passed to function _fetch_device_config")

                # We have raw install data that includes all configurations; find the correct config
                # {
                #   "dums": [ ... ],
                #   "configurations": [
                #     { 
                #        "guid": { "family": "str", "ProductName": "str", "params": [...], ... } 
                #     }
                #   ]
                # }
                ins_configs = raw_install_data.get('configurations') or []

                for ins_config_id, ins_config in ins_configs.items():
                    if ins_config_id == config_id:
                        conf = ins_config
                        conf_id = ins_config_id
                        break

            case DabPumpsFetch.DCONNECT: 
                raw_install_data = None

                context = f"configuration {config_id}"
                request = { "method": "GET", "url":  DCONNECT_API_URL + f"/api/v1/configuration/{config_id}" }
        
                _LOGGER.debug(f"Retrieve device config for '{config_id}'")
                raw = self._send_request(context, request)

                # {
                #    "configuration_id": "id", "name": "some_name", "label": "some_str", "description": "some_str", "metadata": { ... }, ... }
                # }
                conf = raw
                conf_id = None

        # Process the resulting raw data
        conf_id = conf_id or conf.get('configuration_id') or ''
        conf_name = conf.get('name') or conf.get('ProductName') or f"config {conf_id}"
        conf_label = conf.get('label') or conf.get('family') or f"config {conf_id}"
        conf_descr = conf.get('description') or conf.get('ProductName') or f"config {conf_id}"
        conf_params = {}

        if conf_id != config_id: 
            raise DabPumpsDataError(f"Expected configuration id {config_id} was not found in returned configuration data")
            
        meta = conf.get('metadata') or {}
        meta_params = meta.get('params') or conf.get('params') or []
        
        for meta_param_idx, meta_param in enumerate(meta_params):
            # get param details
            param_name = meta_param.get('name') or f"param{meta_param_idx}"
            param_type = meta_param.get('type') or ''
            param_unit = meta_param.get('unit')
            param_weight = meta_param.get('weight')
            param_min = meta_param.get('min') or meta_param.get('warn_low')
            param_max = meta_param.get('max') or meta_param.get('warn_hi')
            param_family = meta_param.get('family') or ''
            param_group = meta_param.get('group') or ''
            param_view = meta_param.get('view') or []
            param_change = meta_param.get('change') or []
            
            values = meta_param.get('values') or []
            param_values = { str(v[0]): self._translate_string(str(v[1])) for v in values if len(v) >= 2 }
            
            param = DabPumpsParams(
                name = self._translate_string(param_name),
                type = param_type,
                unit = param_unit,
                weight = param_weight,
                values = param_values,
                min = param_min,
                max = param_max,
                family = param_family,
                group = param_group,
                view = param_view,
                change = param_change,
            )
            conf_params[param_name] = param
        
        config = DabPumpsDeviceConfig(
            id = conf_id,
            label = conf_label,
            description = conf_descr,
            meta_params = conf_params
        )
        
        if len(conf_params) == 0:
            raise DabPumpsDataError(f"No config found for '{config_id}'")
        
        _LOGGER.debug(f"Configuration found: {conf_name} with {len(conf_params)} metadata params")        

        # Merge with configurations from other devices
        self._device_config_map[conf_id] = config
        

    def _fetch_device_state(self, serial: str, raw_install_data: dict|None = None):
        """Fetch the statuses for a DAB Pumps device"""

        statusts = None
        lastrecv = None
        values = {}

        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS:
                if raw_install_data is None:
                    raise DabPumpsError("No raw install data was passed to function _fetch_device_statuses")
            
                # We have raw install data that includes all devices; find the correct device
                # {
                #   "dums": [
                #     { "configuration_id": "guid3", "serial": "some_str", "statusts": "some_ts, "status": { ... }, ... }
                #   ]
                # }
                ins_dums = raw_install_data.get('dums') or []
            
                for dum in ins_dums:
                    dum_serial = dum.get('serial') or ''
                    if dum_serial == serial:
                        statusts = dum.get('statusts') or ""
                        lastrecv = dum.get('lastreceived') or ""
                        values = dum.get('status') or {}
                        break
        
            case DabPumpsFetch.DCONNECT: 
                # Raw install data does not contain statuses when using this method.
                # Retrieve statuses specific for this device
                context = f"statuses {serial}"
                request = { "method": "GET", "url": DCONNECT_API_URL + f"/dumstate/{serial}" } # or f"/api/v1/dum/{serial}/state"
                
                _LOGGER.debug(f"Retrieve device statuses for '{serial}'")
                raw = self._send_request(context, request)
                
                # {
                #   "statusts": "some_datetime",
                #   "status": "{ "key1": "value1", "key2": "value2", ... }",   as string!
                #   ...
                # }
                statusts = raw.get('statusts') or ""
                lastrecv = raw.get('lastreceived') or ""
                status = raw.get('status') or "{}" # string!
                values = json.loads(status)

        # Process the resulting raw data
        state = self._parse_device_state(serial, statusts, lastrecv, values)

        if len(state.status) == 0:
            raise DabPumpsDataError(f"No statuses found for '{serial}'")
        
        _LOGGER.debug(f"Statuses found for '{serial}' with {len(state.status)} values")

        # Merge with statuses from other devices
        self._device_state_map[serial] = state
        

    def _parse_device_state(self, serial: str, statusts: Any, lastrecv: Any, values: dict) -> DabPumpsDeviceState:
        """
        Heper function to parse received data into a device state.
        Called when data is retrieved via a poll request or via a push from the remote DAB Pumps servers.
        """

        if isinstance(statusts, (int,float)):
            status_ts = datetime.fromtimestamp(statusts/1000.0, tz=timezone.utc)
        elif isinstance(statusts, str):
            status_ts = datetime.fromisoformat(statusts)
        else:
            status_ts = utcnow()

        if isinstance(lastrecv, (int,float)):
            lastrecv_ts = datetime.fromtimestamp(lastrecv/1000.0, tz=timezone.utc)
        elif isinstance(lastrecv, str):
            lastrecv_ts = datetime.fromisoformat(lastrecv)
        else:
            lastrecv_ts = utcmin()

        status: dict[str, DabPumpsStatus] = {}

        for item_key, item_code in values.items():
            try:
                # Check if this status was recently updated via change_device_status
                # We keep the updated value for a hold period to prevent it from flipping back and forth 
                # between its old value and new value because of delays in update on the DAB server side.
                status_old = self.get_status_value(serial, item_key)
                update_ts = self.get_status_update(serial, item_key)

                if status_old is not None and update_ts is not None and \
                    (utcnow() - update_ts).total_seconds() < STATUS_UPDATE_HOLD:

                    _LOGGER.info(f"Skip refresh of recently updated status ({serial}.{item_key})")
                    status[item_key] = status_old
                    continue

                # Resolve the coded value into the real world value
                (item_val, _) = self._decode_status_value(serial, item_key, item_code)

                # Add it to our statuses
                status_new = DabPumpsStatus(
                    code = item_code,
                    value = item_val,
                )
                status[item_key] = status_new

                # Reset update flag
                self.set_status_update(serial, item_key, None)

            except Exception as e:
                _LOGGER.warning(f"Exception while processing status for '{serial}:{item_key}': {e}")

        return DabPumpsDeviceState(
            status_ts = max(status_ts, lastrecv_ts),
            status = status,
        )
    
        
    def _derive_device_details(self, serial: str):
        """
        Derive extra details for a DAB Pumps device

        This function should be run AFTER both _fetch_device_config and _fetch_device_state
        """
    
        device = self._device_map.get(serial)
        device_state = self._device_state_map.get(serial)

        if device is None or device_state is None:
            return

        # Search for specific statuses
        for attr,keys in DEVICE_ATTR_EXTRA.items():
            # Try to find a status for this device and these keys
            status = next( (status for k,status in device_state.status.items() if k in keys), None)
            
            if status is not None and status.value is not None:
                # Found it. Update the device attribute (workaround via dict because it is a namedtuple)
                if getattr(device, attr) != status.value:
                    _LOGGER.debug(f"Found extra device attribute {serial} {attr} = {status.value}")
                    setattr(device, attr, status.value)


    def change_device_status(self, serial: str, key: str, code: str|None=None, value: Any|None=None):
        """
        Set a new status value for a DAB Pumps device.

        Either code (the value as expected by Dab Pumps backend) or value (the real world value)
        needs to be supplied.
        """

        # Sanity check
        if code is None and value is None:
            
            _LOGGER.warning(f"To change device status either 'code' or 'value' needs to be specified")
            return False
        
        state = self._device_state_map.get(serial)
        status = state.status.get(key) if state is not None else None
        if not status:
            # Not found
            return False
        
        # If needed encode the value into what DabPumps backend expects
        if code is None:
            code = self._encode_status_value(serial, key, value)
        else:
            (value,_) = self._decode_status_value(serial, key, code)
            
        if status.code == code:
            # Not changed
            return False
        
        _LOGGER.info(f"Set {serial}:{key} from {status.value} to {value} ({code})")
        
        # update the cached value in device_state_map.status
        state.status[key] = DabPumpsStatus(code = code, value = value)
        self.set_status_update(serial, key, utcnow())
       
        # Update data via REST request
        context = f"set {serial}:{key}"

        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS: url = DABCS_API_URL + f"/mobile/v1/dums/{serial}/setparam?skipLogging=false"
            case DabPumpsFetch.DCONNECT: url = DCONNECT_API_URL + f"/dum/{serial}"
        
        request = {
            "method": "POST",
            "url": url,
            "headers": {
                'Content-Type': 'application/json',
            },
            "json": {
                'key': key, 
                'value': code,
            },
        }
        
        _LOGGER.debug(f"Set device param for '{serial}:{key}' to '{value}'")
        raw = self._send_request(context, request)
        
        # If no exception was thrown then the operation was successfull
        return True
    

    def change_install_role(self, install_id: str, role_old: DabPumpsUserRole, role_new: DabPumpsUserRole):
        """
        Set a new role for the logged in user within a DAB Pumps install.
        """

        # Sanity check
        if role_old not in [DabPumpsUserRole.CUSTOMER, DabPumpsUserRole.INSTALLER] or \
           role_new not in [DabPumpsUserRole.CUSTOMER, DabPumpsUserRole.INSTALLER]:
            
            _LOGGER.warning(f"User role must be customer or installer")
            return False

        match self._login_info.fetch_method:
            case DabPumpsFetch.DABCS: 
                # Delete old role then add new role
                context = f"del {install_id}:{self._username}"
                request = {
                    "method": "DELETE",
                    "url": DABCS_API_URL + f"/mobile/v1/installations/{install_id}/users/{role_old}/{self._username}",
                }
                _LOGGER.debug(f"Del install role")
                raw = self._send_request(context, request)

                context = f"add {install_id}:{self._username}"
                request = {
                    "method": "POST",
                    "url": DABCS_API_URL + f"/mobile/v1/installations/{install_id}/users/{role_new}/{self._username}",
                    "headers": {
                      'Content-Length': '0',
                    },
                }
                _LOGGER.debug(f"Add install role")
                raw = self._send_request(context, request)

            case DabPumpsFetch.DCONNECT: 
                # Get user_id from username
                context = f"user {self._username}"
                request = {
                    "method": "GET",
                    "url": DCONNECT_API_URL + f"/api/v1/user", # or DCONNECT_API_URL + f"/user/{username}/search"
                }
                _LOGGER.debug(f"Get user")
                raw = self._send_request(context, request)

                user_id = raw.get('user_id') or ""

                # Delete old role then add new role
                context = f"del {install_id}:{self._username}"
                request = {
                    "method": "GET",
                    "url": DCONNECT_API_URL + f"/installation/{install_id}/remove/{role_old}/{user_id}",
                }
                _LOGGER.debug(f"Del install role")
                raw = self._send_request(context, request)

                context = f"add {install_id}:{self._username}"
                request = {
                    "method": "GET",
                    "url": DCONNECT_API_URL + f"/installation/{install_id}/add/{role_new}/{user_id}",
                }
                _LOGGER.debug(f"Add install role")
                raw = self._send_request(context, request)
        
        # If no exception was thrown then the operation was successfull
        return True


    def fetch_strings(self, lang: str):
        """Get string translations"""
    
        # Retrieve data via REST request
        context = f"localization_{lang}"
        request = {
            "method": "GET",
            "url": DCONNECT_API_URL + f"/resources/js/localization_{lang}.properties?format=JSON&fullmerge=1",
            "flags": {
                'authorize': False,
            },
        }
        
        _LOGGER.debug(f"Retrieve language info")
        raw = self._send_request(context, request)

        # Process the resulting raw data
        # For DConnect:
        # {
        #   "bundle": "2 letter language code",
        #   "messages": {
        #     "key1": "value1", "key2": "value2", ...
        #   },
        #   ...
        # }
        language = raw.get('bundle') or ''
        messages = raw.get('messages') or {}
        string_map = { k: v for k, v in messages.items() }
        
        # Sanity check. # Never overwrite a known string_map with empty lists
        if len(string_map) == 0:
            raise DabPumpsDataError(f"No strings found in data")

        _LOGGER.debug(f"Strings found: {len(string_map)} in language '{language}'")
        
        # Remember this data
        self._string_map_lang = language
        self._string_map = string_map


    def get_status_value(self, serial: str, key: str) -> DabPumpsStatus:
        """
        Resolve code, value and unit for a status
        """
        state = self._device_state_map.get(serial)
        status = state.status.get(key) if state is not None else None

        # Return status for this key; decoding and translation of code into value is already done.
        return status


    def get_status_metadata(self, serial: str, key: str) -> DabPumpsParams:
        """
        Resolve meta params for a status
        """

        # Find the meta params for this status
        device = self._device_map.get(serial) if self._device_map else None
        config = self._device_config_map.get(device.config_id) if device is not None and self._device_config_map  else None
        params = config.meta_params.get(key) if config is not None and config.meta_params else None

        return params


    def get_status_update(self, serial: str, key: str) -> tuple[str,datetime]:
        """
        Resolve timestamp of last update of the status (if any changes were made)
        """
        update_id = DabPumpsBase.create_id(serial, key)
        update_ts = self._status_update_map.get(update_id)

        return update_ts

    def set_status_update(self, serial: str, key: str, ts: datetime):
        """
        Set/reset timestamp of last update of the status (if any changes were made)
        """
        update_id = DabPumpsBase.create_id(serial, key)
        if ts is not None:
            self._status_update_map[update_id] = ts
        else:
            self._status_update_map.pop(update_id, None)


    def _decode_status_value(self, serial: str, key: str, code: str) -> Any:
        """
        Resolve the coded value into the real world value.
        Also returns the unit of measurement.
        """

        # Find the meta params for this status
        params = self.get_status_metadata(serial, key)
        if params is None:
            return (code, '')
        
        if code is None or code in DabPumpsStatusCode:
            return (code, params.unit)
        
        # param:DabPumpsParams - 'key, type, unit, weight, values, min, max, family, group, view, change'
        match params.type:
            case DabPumpsParamType.ENUM:
                # Lookup value (already translated)
                value = params.values.get(code, code) if params.values is not None else code 

            case DabPumpsParamType.MEASURE:
                if code != '':
                    if params.weight and params.weight != 1 and params.weight != 0:
                        # Convert to float
                        precision = int(math.floor(math.log10(1.0 / params.weight)))
                        value = round(float(code) * params.weight, precision)
                    else:
                        # Convert to int
                        value = int(code)
                else:
                    value = None
                    
            case DabPumpsParamType.LABEL:
                # Convert to string; no translation
                value = str(code)

            case DabPumpsParamType.SETTINGS:
                value = str(code)
            
            case _:
                _LOGGER.warning(f"Encountered an unknown params type '{params.type}' for '{serial}:{key}'. Please contact the integration developer to have this resolved.")
                value = None

        return (value, params.unit)


    def _encode_status_value(self, serial: str, key: str, value: Any) -> Any:
        """
        Resolve the real world value into the coded value.
        """

        # Find the meta params for this status
        params = self.get_status_metadata(serial, key)

        if params is None or value is None:
            return str(value)
        
        # param:DabPumpsParams - 'key, type, unit, weight, values, min, max, family, group, view, change'
        match params.type:
            case DabPumpsParamType.ENUM:
                code = next( (str(k) for k,v in params.values.items() if v==value), None)
                if code is None:
                    code = str(value)

            case DabPumpsParamType.MEASURE:
                if params.weight and params.weight != 1 and params.weight != 0:
                    # Convert from float to int
                    code = str(int(round(value / params.weight)))
                else:
                    # Convert to int
                    code = str(int(value))
                    
            case DabPumpsParamType.LABEL:
                # Convert to string
                code = str(value)

            case DabPumpsParamType.SETTINGS:
                code = str(value)
            
            case _:
                _LOGGER.warning(f"Encountered an unknown params type '{params.type}' for '{serial}:{key}'. Please contact the integration developer to have this resolved.")
                code = None
        
        return code
    

    def _translate_string(self, str: str) -> str:
        """
        Return 'translated' string or original string if not found
        """
        return self._string_map.get(str, str) if self._string_map else str
    

    def _send_request(self, context, request):
        """GET or POST a request for JSON data"""

        timestamp = utcnow()
        flags = request.get("flags") or {}
        flags_redirects = flags.get("redirects", True)
        flags_authorize = flags.get("authorize", True)

        # Always add certain headers
        if not "headers" in request:
            request["headers"] = {}

        if self._login_info.auth_method == DabPumpsAuth.HEADER and self._access_token_info.token and not context.startswith('login') and flags_authorize:
            request["headers"]['Authorization'] = 'Bearer ' + self._access_token_info.token

        if self._login_info.extra_headers:
            request["headers"].update(self._login_info.extra_headers)

        # Add some default headers if not already set via extra_headers
        request["headers"].setdefault('User-Agent', 'DabIopApp/1.8.6')
        request["headers"].setdefault('Cache-Control', 'no-store, no-cache, max-age=0')
        request["headers"].setdefault('Connection', 'close')

        # Perform the request
        try:
            req = self._http_client.build_request(
                method = request["method"],
                url = request["url"],
                params = request.get("params"), 
                data = request.get("data"),
                json = request.get("json"),
                headers = request.get("headers"),
                timeout = httpx.Timeout(HTTPX_REQUEST_TIMEOUT),
            )
            rsp = self._http_client.send(req, follow_redirects=flags_redirects)

            # Remember actual requests and response params, used for diagnostics
            request["headers"] = req.headers
            response = {
                "success": rsp.is_success or rsp.is_redirect,
                "status": f"{rsp.status_code} {rsp.reason_phrase}",
                "headers": rsp.headers,
                "elapsed": (utcnow() - timestamp).total_seconds(),
            }
            if rsp.headers.get('content-type','').startswith('application/json'):
                response["json"] = rsp.json()
            else:
                response["text"] = rsp.text
            
        except Exception as ex:
            error = f"Request failed: exception '{str(ex)}' while trying to reach {request["url"]}"
            _LOGGER.debug(error)

            if flags_authorize:
                # Force a logout to so next login will be a token refresh or real login, not a token reuse
                self._logout(context)
                
            raise DabPumpsConnectError(error)

        # Save the diagnostics if requested
        self._update_diagnostics(timestamp, context, request, response)
        
        # Check response
        if not response["success"]:
            if "json" in response and "error" in response["json"]:
                error = f"Request failed: '{response["json"]["error"]}' while trying to reach {request["url"]}"
            else:
                error = f"Request failed: '{response["status"]}' while trying to reach {request["url"]}"
            _LOGGER.debug(error)

            # Force a logout to so next login will be a token refresh or a real login, not a token reuse
            if "401" in response["status"]:
                self._logout(context)
                raise DabPumpsAuthError(error)
            else:
                raise DabPumpsConnectError(error)
        
        if not flags_redirects and response['status'].startswith("302"):
            return response["headers"].get("location") or ''

        elif "text" in response:
            return response["text"]
        
        elif "json" in response:
            # if the result structure contains a 'res' value, then check it
            json = response["json"]
            res = json.get('res')
            if res and res not in ['OK', 'SCHEDULED']:
                # BAD RESPONSE: { "res": "ERROR", "code": "FORBIDDEN", "msg": "Forbidden operation", "where": "ROUTE RULE" }
                code = json.get('code') or ''
                msg = json.get('msg') or ''
                
                if code.upper() in ['FORBIDDEN', 'WRONGCREDENTIAL']:
                    error = f"Authorization failed: {res} {code} {msg}"
                    _LOGGER.debug(error)

                    # Force a logout to so next login will be a token refresh or a real login, not a token reuse
                    self._logout(context)
                    raise DabPumpsAuthError(error)
                else:
                    error = f"Request failed: {res} {code} {msg} while trying to reach {request["url"]}"
                    _LOGGER.debug(error)
                    raise DabPumpsError(error)

            return json
        
        else:
            return None
    

    def _update_diagnostics(self, timestamp: datetime, context: str, request: dict|None, response: dict|None, token: dict|None = None):

        if self._diagnostics_callback:
            item = DabPumpsHistoryItem.create(timestamp, context, request, response, token)
            detail = DabPumpsHistoryDetail.create(timestamp, context, request, response, token)
            data = {
                "login_info": self._login_info,
                "access_token_info": self._access_token_info,
                "refresh_token_info": self._refresh_token_info,
                "session_info": self._session_info,

                "string_map_lang": self.string_map_lang,
            }

            self._diagnostics_callback(context, item, detail, data)
    

